#!/bin/bash

# filtered by type and environment (type is optional)
getRegistrationsWithLineNumbers() {
    lineNumber=1
    while read registration;
    do
        env=`echo ${registration} | cut -d" " -f2`
        if [ ${KB_ENVIRONMENT} ] && [ "$env" != "$KB_ENVIRONMENT" ]
        then
            continue;
        fi

        type=`echo ${registration} | cut -d" " -f4-`
        if [ $1 ] && [ "$1" != "$type" ]
        then
            continue;
        fi

        echo ${lineNumber} ${registration}
        lineNumber=$[$lineNumber + 1]
    done < $KB_REGISTRATION_FILE
}

# filtered by type and environment (type is optional)
getRegistrations() {
    lineNumber=0
    while read registration;
    do
        env=`echo ${registration} | cut -d" " -f2`
        if [ ${KB_ENVIRONMENT} ] && [ "$env" != "$KB_ENVIRONMENT" ]
        then
            continue;
        fi

        type=`echo ${registration} | cut -d" " -f4-`
        if [ $1 ] && [ "$1" != "$type" ]
        then
            continue;
        fi

        lineNumber=$[$lineNumber + 1]
        if [ $2 ] && [ $2 -ne ${lineNumber} ]
        then
            continue;
        fi

        echo ${registration}
    done < $KB_REGISTRATION_FILE
}
