#!/bin/bash

# Lists virtual machines in prsim for a specific environment

if [[ $# -lt 1 || "$1" = "help" ]]
then
    echo "Syntax: machines <environment>"
    exit 0
fi

curl -s -u readonly:"readonly" "${KB_PRISM_HOST}/cmdb_api/v1/system/?status!=decommissioned&environment_name~${1}&page=1&start=0&limit=25" | ${KB_HOME}/parseMachines.py