#!/bin/bash

# SSH to hosts

if [ "$1" = "help" ]
then
    echo "Syntax: ssh <type> <{<index> | all}> <command>"
    exit 0
fi

source functions

if [ "$2" = "all" ]
then
    rm ${KB_HOME}/hosts
    getHostnameFromRegistrations $1 > ${KB_HOME}/hosts

    if [ -s ${KB_HOME}/hosts ]
    then
        shift;shift
        pssh -i -h ${KB_HOME}/hosts $@
    else
        echo "No hosts match"
    fi
else
    hostname=`getHostnameFromRegistrations $1 $2`

    if [ $hostname ]
    then
        shift;shift
        ssh -t ${hostname} $@
    else
        echo "No hosts match"
    fi
fi