#!/bin/bash

# SSH to hosts

if [ "$1" = "help" ]
then
    echo "Syntax: ssh <type> <{<index> | all}> <command>"
    exit 0
fi

source functions

if [ "$2" = "all" ]
then
    rm ${KB_HOME}/hosts 2>&1
    getRegistrations $1 | cut -d" " -f1 > ${KB_HOME}/hosts

    if [ -s ${KB_HOME}/hosts ]
    then
        shift;shift
        pssh -i -x "-o ProxyCommand=\"ssh -A -W %h:%p m0051661.lab.ppops.net\"" -h ${KB_HOME}/hosts $@
    else
        echo "No hosts match"
    fi
else
    registration=`getRegistrations $1 $2`
    hostname=`echo ${registration} | cut -d" " -f1`
    cloud=`echo ${registration} | cut -d" " -f3`

    if [ ${hostname} ]
    then
        shift;shift

        if [ "${cloud}" = "awslabcloud" ]
        then
#            ssh -t -o ProxyCommand="ssh -A -W %h:%p m0051661.lab.ppops.net" ${hostname} $@
            ssh -t -o ProxyCommand="ssh -A -W %h:%p m0051672.lab.ppops.net" ${hostname} $@
        else
            ssh -t ${hostname} $@
        fi
    else
        echo "No hosts match"
    fi
fi