#!/bin/bash

# TODO add notifications?

# KB Environment variables
home=`dirname $0`
export KB_HOME=$home/kb_commands
export KB_DEFAULT_REGISTRATION_FILE=${KB_HOME}/default_registrations
export KB_REGISTRATION_FILE=${KB_HOME}/registrations
export KB_VARIABLES_FILE=${KB_HOME}/variables
export KB_LAB_PRISM_HOST="<lab host>"
export KB_PRODUCTION_PRISM_HOST="<production host"
export KB_USERNAME=jsabin

# Add KB scripts to path
export PATH=$PATH:${KB_HOME}

# Setup autocomplete
$KB_HOME/setupautocomplete.sh

# Load KB specific variables from file
source $KB_HOME/variables

# Load current environment from file
source $KB_HOME/environment

# Case insensitive
#shopt -s nocasematch

# TODO error if parameter is missing
#${1:?"mkjail: Missing operand"}


command=kb_$1
shift

commandLineArray=()
for argument in "$@"
do
    line="\"$argument\""

    # Replace ^ with $ and evaluate variable
    line=${line/"^"/"$"}

    commandLineArray+=($line);
done


# Call into KB command
eval $command "${commandLineArray[@]}"









