#!/bin/bash

# Lists virtual machines in prsim for a specific environment

if [[ (! ${KB_ENVIRONMENT} && $# -lt 1 )|| "$1" = "help" ]]
then
    echo "Syntax: machines <environment>"
    exit 0
fi

environment=$1
if [[ ! $1 && ${KB_ENVIRONMENT} ]]
then
    environment=${KB_ENVIRONMENT}
fi
curl -s -u foo:"foo" "${KB_LAB_PRISM_HOST}/cmdb_api/v1/system/?status!=decommissioned&environment_name~${environment}&page=1&start=0&limit=25" | ${KB_HOME}/parseMachines.py